import { FileContentTypesEnum, RepoPathsEnum } from './types';

export const FILE_EXTENSION = 'json';

export const DEFAULT_REPO_DESCRIPTION = 'Repository automatically generated by Safis CMS.';

export const repoPathTransforms = {
  [FileContentTypesEnum.CONTENT]: RepoPathsEnum.CONTENT,
  [FileContentTypesEnum.CONTENT_TYPE]: RepoPathsEnum.CONTENT_TYPE,
};
